"""1級大問1の暗記カード用に、オリジナル例文と日本語訳を適用する。"""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = ROOT / "data"


# 公式問題の設問文は使わず、各語句の意味が文脈から分かる英文を収録する。
EXAMPLES = {
    "2025-2": {
        "embezzlement": ("The accountant was arrested for embezzlement after investigators found money missing from several accounts.", "捜査官が複数の口座から金がなくなっていることを発見した後、その会計士は横領の容疑で逮捕された。"),
        "notoriety": ("The small town gained notoriety after a series of unexplained fires.", "その小さな町は、原因不明の火災が相次いだことで悪名を得た。"),
        "fortitude": ("She showed remarkable fortitude while caring for her injured brother.", "彼女はけがをした弟の世話をする間、並外れた不屈の精神を示した。"),
        "cessation": ("The treaty called for the immediate cessation of hostilities.", "その条約は敵対行為の即時停止を求めていた。"),
        "clatter": ("The clatter of dishes woke the baby.", "食器がガチャガチャ鳴る音で赤ん坊が目を覚ました。"),
        "acclaim": ("The director's first film won international acclaim.", "その監督の初作品は国際的な称賛を浴びた。"),
        "bigotry": ("The organization works to combat bigotry in schools and workplaces.", "その組織は学校や職場での偏見と闘っている。"),
        "dogma": ("The scientist questioned the dogma that intelligence is fixed at birth.", "その科学者は、知能は生まれた時に決まっているという定説に疑問を呈した。"),
        "gaunt": ("After months at sea, the rescued sailors looked gaunt and exhausted.", "何か月も海上にいた後、救助された船員たちはやせこけ、疲れ果てていた。"),
        "meager": ("The hikers survived on a meager supply of rice.", "ハイカーたちはわずかな米の蓄えで生き延びた。"),
        "rife": ("The report found that corruption was rife in the procurement process.", "その報告書は、調達過程に汚職がはびこっていることを明らかにした。"),
        "virile": ("The novel portrays the young explorer as virile and confident.", "その小説は若い探検家を精力旺盛で自信に満ちた人物として描いている。"),
        "invigorated": ("A walk in the mountain air left the hikers invigorated.", "山の空気の中を歩いたことで、ハイカーたちは元気づけられた。"),
        "provincial": ("The magazine criticized the mayor's provincial view of international affairs.", "その雑誌は、市長の国際情勢に対する視野の狭い見方を批判した。"),
        "contiguous": ("The two parks form one contiguous area of protected forest.", "その二つの公園は、一続きの保護林区域を形成している。"),
        "tenuous": ("The researchers found only a tenuous link between the two events.", "研究者たちは、その二つの出来事の間にかすかなつながりしか見いだせなかった。"),
        "collate": ("Please collate the survey responses before the meeting.", "会議の前にアンケートの回答を照合してください。"),
        "revoke": ("The agency may revoke the license if the company violates safety rules.", "その会社が安全規則に違反すれば、当局は免許を取り消す可能性がある。"),
        "bemoan": ("Residents bemoaned the loss of the old theater.", "住民たちは古い劇場が失われたことを嘆いた。"),
        "thwart": ("A security guard thwarted the attempt to enter the building.", "警備員が建物に侵入しようとする企てを妨げた。"),
        "paramount": ("In an emergency, protecting human life is paramount.", "緊急時には、人命を守ることが最も重要だ。"),
        "haphazard": ("The files were stored in a haphazard way, making them difficult to find.", "ファイルは無計画に保管されていたため、見つけるのが難しかった。"),
        "pristine": ("Divers discovered a pristine coral reef far from the coast.", "ダイバーたちは海岸から遠く離れた場所で、汚れのないサンゴ礁を発見した。"),
        "heedless": ("He was heedless of the warning signs and entered the unstable tunnel.", "彼は警告標識を気に留めず、不安定なトンネルに入った。"),
        "implored": ("The villagers implored the authorities to repair the bridge.", "村人たちは当局に橋を修理するよう懇願した。"),
        "purged": ("The software update purged thousands of duplicate files.", "そのソフトウェアの更新によって、何千もの重複ファイルが一掃された。"),
        "reverted": ("After the trial period ended, the system reverted to its original settings.", "試用期間が終わると、システムは元の設定に戻った。"),
        "grafted": ("The farmer grafted a pear branch onto a stronger tree.", "農家の人は、より丈夫な木に梨の枝を接ぎ木した。"),
        "demeanor": ("Despite the pressure, the witness maintained a calm demeanor.", "その証人は、プレッシャーにもかかわらず落ち着いた態度を保った。"),
        "discretion": ("The editor used discretion when deciding which details to publish.", "編集者はどの詳細を公表するか決める際に慎重さを示した。"),
        "congeniality": ("Her warmth and congeniality made new employees feel welcome.", "彼女の温かさと親しみやすさは、新入社員に歓迎されていると感じさせた。"),
        "bravado": ("His loud bravado disappeared when the real danger approached.", "本当の危険が迫ると、彼の大げさな強がりは消えた。"),
        "enervating": ("The enervating heat made it difficult to concentrate.", "精力を奪う暑さのため、集中するのが難しかった。"),
        "jarring": ("The sudden change from silence to loud music was jarring.", "静けさから大音量の音楽へ突然変わったことは、耳障りで調和を乱すものだった。"),
        "impregnable": ("The fortress was considered impregnable until a hidden passage was discovered.", "その要塞は、隠し通路が発見されるまで攻略不能だと考えられていた。"),
        "precocious": ("The precocious child was reading novels by the age of six.", "その早熟な子どもは6歳までに小説を読んでいた。"),
        "diminutive": ("The diminutive device can fit inside a pocket.", "その小型の装置はポケットに入る。"),
        "superficial": ("The report offered only a superficial analysis of the problem.", "その報告書は問題を表面的に分析しただけだった。"),
        "tedious": ("Copying the data by hand was a tedious task.", "データを手で写すのは退屈な作業だった。"),
        "intrepid": ("The intrepid climber continued toward the summit despite the storm.", "その恐れを知らない登山家は、嵐にもかかわらず頂上へ進み続けた。"),
        "proclaimed": ("The newly elected leader proclaimed that transparency would be a priority.", "新たに選出された指導者は、透明性を優先すると宣言した。"),
        "quenched": ("A glass of cold water quenched her thirst after the run.", "走った後、冷たい水一杯が彼女の喉の渇きを癒やした。"),
        "incarcerated": ("The incarcerated man spent years studying law in prison.", "その投獄された男性は、刑務所で何年も法律を学んだ。"),
        "synthesized": ("The researchers synthesized a new compound in the laboratory.", "研究者たちは実験室で新しい化合物を合成した。"),
        "discord": ("The disagreement created discord among the members of the committee.", "その意見の不一致は委員会のメンバーの間に不和を生んだ。"),
        "heresy": ("At the time, the claim that Earth moved around the sun was treated as heresy.", "当時、地球が太陽の周りを動くという主張は異端説とみなされた。"),
        "credence": ("The new evidence gave credence to the witness's account.", "新しい証拠は、その証人の説明に信憑性を与えた。"),
        "germination": ("Adequate moisture is essential for the germination of seeds.", "種子の発芽には十分な水分が不可欠だ。"),
        "deferentially": ("The young diplomat spoke deferentially to the ambassador.", "若い外交官は大使に敬意を払って話した。"),
        "sequentially": ("The files must be numbered sequentially before they are archived.", "ファイルは保管する前に順番に番号を付けなければならない。"),
        "slenderly": ("The willow branches hung slenderly over the pond.", "柳の枝は池の上に細長く垂れ下がっていた。"),
        "discreetly": ("She discreetly placed the letter in his bag.", "彼女は目立たないようにその手紙を彼のかばんに入れた。"),
        "liaison": ("A liaison between the two hospitals improved emergency care.", "二つの病院の連携によって救急医療が改善した。"),
        "entreaty": ("At her parents' entreaty, he agreed to reconsider the decision.", "彼女の両親の懇願を受けて、彼はその決定を考え直すことに同意した。"),
        "levity": ("The speaker used a little levity to ease the tension in the room.", "話し手は部屋の緊張を和らげるために、少し軽口を交えた。"),
        "consignment": ("The store received a consignment of handmade furniture from Italy.", "その店はイタリアから手作り家具の委託品を受け取った。"),
        "buttressing": ("The new data provide important buttressing for the researchers' argument.", "新しいデータは研究者たちの主張を重要な形で支えている。"),
        "assassination": ("The assassination of the president plunged the country into mourning.", "大統領の暗殺によって、その国は悲しみに包まれた。"),
        "digression": ("After a brief digression, the professor returned to the main argument.", "短い余談の後、教授は主な論点に戻った。"),
        "coup": ("Winning the contract was a major coup for the young company.", "その契約を勝ち取ったことは、その若い会社にとって大きな成功だった。"),
        "spurious": ("The article was based on a spurious claim about the vaccine.", "その記事はワクチンについての根拠のない主張に基づいていた。"),
        "ailing": ("The government introduced a rescue plan for the ailing airline.", "政府は経営不振の航空会社のために救済計画を導入した。"),
        "overt": ("The report revealed an overt attempt to influence the election.", "その報告書は選挙に影響を与えようとする公然の試みを明らかにした。"),
        "magnanimous": ("The champion was magnanimous toward the opponent who had made a costly mistake.", "その優勝者は大きなミスをした対戦相手に対して寛大だった。"),
        "jilted": ("The jilted bride canceled the wedding and left town.", "婚約を破棄された花嫁は結婚式を取りやめ、町を去った。"),
        "duped": ("Several tourists were duped by a fake ticket seller.", "何人もの観光客が偽のチケット販売員にだまされた。"),
        "slanted": ("The newspaper was criticized for its slanted coverage of the protest.", "その新聞は抗議活動を偏った形で報道したとして批判された。"),
        "scampered": ("The frightened fox scampered into the bushes.", "おびえたキツネは茂みの中へちょこちょこ走り去った。"),
        "scrawl": ("Her hurried scrawl was difficult to read.", "彼女が急いで書いた走り書きは読みにくかった。"),
        "percolate": ("It took time for the new idea to percolate through the organization.", "新しい考えが組織全体に浸透するには時間がかかった。"),
        "pawn": ("He had to pawn his guitar to pay the rent.", "彼は家賃を払うためにギターを質に入れなければならなかった。"),
        "sully": ("One careless remark could sully her reputation.", "不用意な発言一つで、彼女の評判が傷つく可能性がある。"),
        "pony up": ("Everyone had to pony up ten dollars for the shared meal.", "全員が食事代として10ドルずつ支払わなければならなかった。"),
        "buckle down": ("With the exam approaching, I decided to buckle down and study.", "試験が近づいたので、私は本腰を入れて勉強することにした。"),
        "foul up": ("A single typo can foul up the entire order.", "たった一つのタイプミスで注文全体がめちゃくちゃになることがある。"),
        "cast down": ("The rejection cast her down, but she soon tried again.", "不合格の知らせで彼女は落胆したが、すぐにもう一度挑戦した。"),
        "breeze in": ("She tends to breeze in late and act as if nothing has happened.", "彼女は遅れてふらりと入ってきて、何事もなかったように振る舞いがちだ。"),
        "branch off": ("At the old bridge, the main trail begins to branch off toward the lake.", "古い橋のところで、本道が湖に向かって分岐し始める。"),
        "crack down": ("The city promised to crack down on illegal dumping.", "市は不法投棄を厳しく取り締まると約束した。"),
        "lop off": ("The gardener used shears to lop off the dead branches.", "庭師ははさみで枯れた枝を切り落とした。"),
        "dwell on": ("Try not to dwell on a mistake you cannot change.", "変えられない失敗について、くよくよ考えないようにしなさい。"),
        "reel off": ("The contestant could reel off the names of every capital in Europe.", "その出場者はヨーロッパのすべての首都の名前を次々とすらすら言えた。"),
        "rustle up": ("I can rustle up a simple dinner before the guests arrive.", "客が到着する前に、簡単な夕食なら急いで用意できる。"),
        "haul off": ("The workers used a crane to haul off the damaged vehicle.", "作業員たちはクレーンを使って壊れた車を運び去った。"),
        "fritter away": ("He frittered away his savings on gadgets he rarely used.", "彼はほとんど使わない機器に貯金を浪費した。"),
        "rip off": ("The shop tried to rip off the tourist.", "その店は観光客からぼったくろうとした。"),
        "sound off": ("He likes to sound off about politics at dinner.", "彼は夕食時に政治について偉そうに意見をぶちまけるのが好きだ。"),
        "crop up": ("Unexpected problems can crop up during any large project.", "どんな大きな計画でも、予想外の問題が不意に起こることがある。"),
    },
    "2025-3": {
        "backlog": ("The support team worked late to clear its backlog of customer requests.", "サポートチームは顧客からの未処理の依頼の山を片付けるため遅くまで働いた。"),
        "upheaval": ("The merger caused considerable upheaval throughout the company.", "その合併は会社全体にかなりの混乱を引き起こした。"),
        "outreach": ("The hospital expanded its outreach to people in remote villages.", "その病院は遠隔地の村の人々への支援活動を拡大した。"),
        "hindsight": ("In hindsight, we should have checked the forecast before sailing.", "後から考えれば、出航前に天気予報を確認すべきだった。"),
        "appeased": ("The manager appeased the angry customer by offering a full refund.", "店長は全額返金を申し出て、怒った客をなだめた。"),
        "expounded": ("During the lecture, the professor expounded on the causes of inflation.", "講義の中で、教授はインフレの原因を詳しく説明した。"),
        "peddled": ("The salesman peddled miracle cures to unsuspecting customers.", "その販売員は何も知らない客に奇跡の治療薬を売り歩いた。"),
        "rescinded": ("The university rescinded the offer after discovering that the documents were forged.", "大学は書類が偽造されていたことを発見した後、申し出を取り消した。"),
        "grime": ("Years of grime covered the windows of the abandoned station.", "何年もの汚れが廃駅の窓を覆っていた。"),
        "ridge": ("We followed the narrow ridge until we reached the summit.", "私たちは頂上に着くまで狭い尾根をたどった。"),
        "glaze": ("The baker used a lemon glaze to finish the cake.", "そのパン職人はケーキの仕上げにレモンの糖衣を使った。"),
        "niche": ("The company found a profitable niche by designing tools for left-handed musicians.", "その会社は左利きの音楽家向けの道具を設計して、利益の出る隙間市場を見つけた。"),
        "posterity": ("The author revised the manuscript carefully for the benefit of posterity.", "その作家は後世の人々のために原稿を注意深く改訂した。"),
        "quarantine": ("The sick dog was kept in quarantine until the test results came back.", "病気の犬は検査結果が出るまで隔離された。"),
        "tempest": ("The fishing boats returned to port before the tempest reached the coast.", "漁船は暴風雨が海岸に到達する前に港へ戻った。"),
        "saturation": ("The market is close to saturation, so further growth will be difficult.", "市場は飽和状態に近いため、さらなる成長は難しいだろう。"),
        "incursion": ("The army responded quickly to an incursion across the border.", "軍は国境を越えた侵入にすぐ対応した。"),
        "grievance": ("The union filed a formal grievance over unsafe working conditions.", "労働組合は安全でない労働条件について正式な苦情を申し立てた。"),
        "enigma": ("The sudden disappearance remains an enigma to investigators.", "その突然の失踪は、今も捜査官にとって謎のままだ。"),
        "query": ("The database can handle a query in less than a second.", "そのデータベースは1秒未満で質問処理を実行できる。"),
        "fastidious": ("The fastidious chef inspected every ingredient before service.", "細かいことにうるさいその料理人は、営業前にすべての食材を調べた。"),
        "exuberant": ("The exuberant crowd sang long after the team had left the field.", "熱狂的な観客はチームが競技場を去った後も長く歌い続けた。"),
        "unassuming": ("Despite her success, she remained unassuming and approachable.", "成功していたにもかかわらず、彼女は控えめで親しみやすいままだった。"),
        "anonymous": ("An anonymous donor paid for the children's medical treatment.", "匿名の寄付者が子どもたちの治療費を支払った。"),
        "brusquely": ("The receptionist brusquely told us that the office was closed.", "受付係は事務所は閉まっていると、ぶっきらぼうに私たちへ告げた。"),
        "surreptitiously": ("He surreptitiously checked his phone during the meeting.", "彼は会議中にこっそり携帯電話を確認した。"),
        "cordially": ("The two former rivals greeted each other cordially at the ceremony.", "かつてのライバル同士は式典で丁重にあいさつを交わした。"),
        "ploddingly": ("The old machine moved ploddingly up the hill.", "古い機械は丘をのろのろと上っていった。"),
        "impasse": ("Negotiations reached an impasse when neither side would compromise.", "どちらの側も妥協しなかったため、交渉は行き詰まった。"),
        "contempt": ("She spoke about the proposal with open contempt.", "彼女はその提案についてあからさまな軽蔑を込めて話した。"),
        "jeopardy": ("The discovery placed the entire project in jeopardy.", "その発見によってプロジェクト全体が危険にさらされた。"),
        "futility": ("The repeated failures made him question the futility of the campaign.", "度重なる失敗によって、彼はその活動の無益さを疑うようになった。"),
        "plantations": ("The region is known for its tea plantations.", "その地域は茶の大農園で知られている。"),
        "sockets": ("The technician replaced the damaged electrical sockets.", "技術者は壊れた電気ソケットを交換した。"),
        "provisions": ("The hikers carried enough provisions for a week.", "ハイカーたちは1週間分の食料を運んだ。"),
        "ventures": ("The entrepreneur has launched several successful ventures.", "その起業家はいくつもの成功した事業を立ち上げてきた。"),
        "percolated": ("The smell of coffee percolated through the house.", "コーヒーの香りが家中にしみ渡った。"),
        "contorted": ("His face contorted in pain when he touched the wound.", "彼が傷に触れると、顔が痛みでゆがんだ。"),
        "tarnished": ("The scandal tarnished the minister's reputation.", "そのスキャンダルは大臣の評判を傷つけた。"),
        "appraised": ("The antique was appraised at twice the price the owner expected.", "その骨董品は、所有者の予想の2倍の価格で査定された。"),
        "buttress": ("The additional evidence will buttress our argument in court.", "追加の証拠は法廷で私たちの主張を支えるだろう。"),
        "cajole": ("She tried to cajole her brother into lending her the car.", "彼女は弟を甘言で説得して車を貸してもらおうとした。"),
        "redeem": ("The athlete hoped to redeem himself after his earlier mistake.", "その選手は先ほどのミスの後で名誉を挽回したいと望んだ。"),
        "gratify": ("It gratified the teacher to see her students working together.", "生徒たちが協力しているのを見て、教師は満足した。"),
        "translucent": ("The translucent curtains let in light while preserving privacy.", "半透明のカーテンはプライバシーを守りながら光を通した。"),
        "fortuitous": ("A fortuitous encounter led her to the job of her dreams.", "偶然の出会いが、彼女を夢の仕事へ導いた。"),
        "inane": ("The committee wasted an hour debating an inane proposal.", "委員会はばかげた提案の議論に1時間を浪費した。"),
        "pampered": ("The pampered puppy refused to sleep anywhere but its owner's bed.", "甘やかされた子犬は飼い主のベッド以外では寝ようとしなかった。"),
        "scamper": ("The children scampered across the yard when the rain began.", "雨が降り始めると、子どもたちは庭をちょこちょこ走り回った。"),
        "wrest": ("The rebels managed to wrest control of the port from the government.", "反乱軍は政府から港の支配権を奪い取ることに成功した。"),
        "peek": ("She took a quick peek at the answers before closing the book.", "彼女は本を閉じる前に答えをちらっとのぞき見した。"),
        "belittle": ("A good leader corrects mistakes without belittling the people who made them.", "よい指導者は、ミスをした人をけなすことなく間違いを正す。"),
        "rotund": ("The rotund professor laughed loudly at his own joke.", "丸々とした教授は自分の冗談に大声で笑った。"),
        "malevolent": ("The villagers believed that a malevolent spirit haunted the forest.", "村人たちは悪意のある精霊が森に取りついていると信じていた。"),
        "ascetic": ("The monk lived an ascetic life with few possessions.", "その僧侶はほとんど財産を持たず、禁欲的な生活を送った。"),
        "tacit": ("Their tacit agreement allowed the project to continue without a formal vote.", "彼らの暗黙の合意によって、正式な投票なしに計画を続けることができた。"),
        "vertical": ("The climber pulled herself up the nearly vertical wall.", "その登山家は、ほぼ垂直の壁をよじ登った。"),
        "intangible": ("Trust is an intangible asset that takes years to build.", "信頼は築くのに何年もかかる無形の財産だ。"),
        "squeamish": ("He is squeamish about blood and avoids medical dramas.", "彼は血を見るのを嫌がり、医療ドラマを避けている。"),
        "enraptured": ("The audience sat enraptured as the violinist began the final movement.", "バイオリニストが最終楽章を始めると、観客は夢中になって聴き入った。"),
        "lanky": ("The lanky teenager had to duck beneath the low doorway.", "ひょろ長いその十代の若者は、低い戸口の下で身をかがめなければならなかった。"),
        "vivacious": ("Her vivacious personality made the quiet room feel lively.", "彼女の生き生きした性格は、静かな部屋を活気づけた。"),
        "mutinous": ("The captain faced a mutinous crew after months without pay.", "船長は何か月も給料を受け取っていない反抗的な乗組員に直面した。"),
        "dilapidated": ("They renovated a dilapidated farmhouse on the edge of the village.", "彼らは村のはずれにあるぼろぼろの農家を改修した。"),
        "caustic": ("The columnist's caustic remarks drew criticism from both parties.", "そのコラムニストの辛辣な発言は両党から批判を招いた。"),
        "ticklish": ("The negotiations are at a ticklish stage, so every word matters.", "交渉は扱いの難しい段階にあるので、一言一言が重要だ。"),
        "subversive": ("The regime accused the journalists of spreading subversive ideas.", "その政権はジャーナリストたちが体制転覆を企てる思想を広めていると非難した。"),
        "impromptu": ("We held an impromptu meeting in the hallway.", "私たちは廊下で即席の会議を開いた。"),
        "repulsed": ("The smell of spoiled milk repulsed the entire kitchen staff.", "腐った牛乳のにおいは厨房のスタッフ全員に強い嫌悪感を抱かせた。"),
        "extolled": ("The review extolled the novel's vivid characters.", "その書評は小説の生き生きした登場人物を大いに褒めた。"),
        "conciliated": ("The mediator conciliated the two neighbors after their dispute.", "調停人は争いの後、二人の隣人を和解させた。"),
        "bungled": ("The contractor bungled the repair and caused even more damage.", "請負業者は修理にへまをして、さらに被害を大きくした。"),
        "nod off": ("I started to nod off during the long train ride.", "長い列車の旅の途中で、私はうとうとし始めた。"),
        "pipe down": ("The teacher asked the students to pipe down.", "先生は生徒たちに静かにするよう求めた。"),
        "drone on": ("The speaker continued to drone on about minor details.", "話し手は細かな点について、だらだらと話し続けた。"),
        "crank out": ("The small factory can crank out hundreds of parts a day.", "その小さな工場は1日に何百個もの部品を次々と作り出せる。"),
        "tail off": ("The applause began to tail off as the lights came up.", "照明が明るくなるにつれて、拍手は次第に弱まった。"),
        "patch up": ("The two friends managed to patch up their disagreement.", "二人の友人は何とか意見の食い違いを修復した。"),
        "choke off": ("The new regulations could choke off investment in the region.", "新しい規制はその地域への投資を抑え込む可能性がある。"),
        "own up": ("He refused to own up to the mistake.", "彼はそのミスを認めようとしなかった。"),
        "hush up": ("The company tried to hush up the safety violation.", "その会社は安全規則違反をもみ消そうとした。"),
        "get behind": ("The campaign needs volunteers to get behind its environmental goals.", "その運動は環境目標を支持するボランティアを必要としている。"),
        "plug in": ("Please plug in the printer before the presentation begins.", "発表が始まる前にプリンターを接続してください。"),
        "farm out": ("The publisher decided to farm out the editing to a specialist.", "出版社は編集作業を専門家に外注することに決めた。"),
        "sit by": ("We cannot sit by while the river is being polluted.", "川が汚染されている間、私たちは傍観しているわけにはいかない。"),
        "dive in": ("Once the instructions were clear, the students were eager to dive in.", "説明が明確になると、生徒たちはすぐに取りかかりたがった。"),
        "strike back": ("The army warned that it would strike back if attacked.", "軍は攻撃されたら反撃すると警告した。"),
        "pan out": ("The plan did not pan out as we had hoped.", "その計画は私たちが望んだようにはうまくいかなかった。"),
    },
    "2026-1": {
        "consolidated": ("The company consolidated its regional offices into one headquarters.", "その会社は地域ごとの事務所を一つの本部に統合した。"),
        "equivocated": ("When asked whether he had accepted the bribe, the official equivocated.", "賄賂を受け取ったのか尋ねられると、その役人は言葉を濁した。"),
        "alleviated": ("The medicine alleviated her pain within an hour.", "その薬は1時間以内に彼女の痛みを和らげた。"),
        "emanated": ("A pleasant smell emanated from the bakery.", "パン屋から心地よい香りが発していた。"),
        "mutter": ("He began to mutter when the computer froze.", "コンピューターが動かなくなると、彼はぶつぶつ言い始めた。"),
        "bolster": ("The scholarship will bolster her chances of attending university.", "その奨学金は彼女が大学へ進学できる可能性を高めるだろう。"),
        "lament": ("Many residents lament the loss of the old market.", "多くの住民が古い市場の喪失を嘆いている。"),
        "spar": ("The two candidates continued to spar over economic policy.", "二人の候補者は経済政策をめぐってつばぜり合いを続けた。"),
        "defer": ("The committee decided to defer the vote until more evidence was available.", "委員会は、さらに証拠が得られるまで投票を延期することに決めた。"),
        "elucidate": ("The diagram helps elucidate the relationship between the two systems.", "その図は二つのシステムの関係を明らかにするのに役立つ。"),
        "solicit": ("The charity will solicit donations from local businesses.", "その慈善団体は地元企業に寄付を求める予定だ。"),
        "dissipate": ("The morning fog began to dissipate as the sun rose.", "日が昇るにつれて、朝霧が消散し始めた。"),
        "torments": ("The torments of exile haunted the poet for years.", "亡命の苦しみは何年もの間、その詩人を悩ませた。"),
        "buskers": ("The subway station is popular with buskers who attract large crowds.", "その地下鉄駅は大勢の人を引きつける路上演奏者たちに人気がある。"),
        "vestiges": ("Only a few vestiges of the ancient wall remain.", "古代の壁の名残はわずかしか残っていない。"),
        "envoys": ("The envoys met privately to discuss a cease-fire.", "使節たちは停戦について話し合うため非公開で会談した。"),
        "stooge": ("The corrupt businessman used a stooge to sign the documents.", "その腐敗した実業家は書類に署名させるため手先を使った。"),
        "extraterrestrial": ("Scientists continue to search for signs of extraterrestrial life.", "科学者たちは地球外生命の兆候を探し続けている。"),
        "incumbent": ("The incumbent mayor is seeking a third term.", "現職の市長は3期目を目指している。"),
        "pilgrim": ("Each pilgrim carried a small bottle of water along the desert route.", "それぞれの巡礼者は砂漠の道を進む間、小さな水筒を携えていた。"),
        "inherent": ("Every technology has inherent limitations.", "どのような技術にも固有の限界がある。"),
        "eccentric": ("The eccentric inventor filled his house with homemade machines.", "その風変わりな発明家は自作の機械で家をいっぱいにした。"),
        "auspicious": ("The clear skies were an auspicious sign for the outdoor ceremony.", "晴れた空は屋外式典にとって幸先のよい兆しだった。"),
        "ornate": ("The palace is famous for its ornate ceilings.", "その宮殿は装飾過多の天井で有名だ。"),
        "pertinent": ("Please limit your comments to facts pertinent to the case.", "発言は事件に関係のある事実に限ってください。"),
        "contrite": ("The contrite student apologized to everyone affected by the prank.", "深く後悔したその生徒は、いたずらの影響を受けた全員に謝った。"),
        "dubious": ("The committee rejected the dubious claim because it lacked evidence.", "委員会は証拠のない疑わしい主張を退けた。"),
        "lucrative": ("Software development became a lucrative career for her.", "ソフトウェア開発は彼女にとってもうかる職業になった。"),
        "obliterated": ("The old bridge was obliterated by the flood.", "古い橋は洪水によって完全に破壊された。"),
        "concocted": ("The witness concocted a story to explain his absence.", "その証人は欠席を説明するために話をでっち上げた。"),
        "acclimated": ("After a few weeks, the recruits became acclimated to the cold climate.", "数週間後、新兵たちは寒い気候に慣れた。"),
        "deduced": ("From the footprints, the detective deduced that two people had entered.", "探偵は足跡から、二人が入ったと推論した。"),
        "queasy": ("The rough sea made several passengers feel queasy.", "荒れた海で、何人もの乗客が吐き気を感じた。"),
        "staunch": ("She remained a staunch supporter of public libraries.", "彼女は公共図書館の忠実な支持者であり続けた。"),
        "porous": ("The porous rock allowed water to pass through.", "その多孔性の岩石は水を通した。"),
        "scruffy": ("A scruffy dog followed us home from the station.", "だらしなく薄汚れた犬が駅から私たちの家までついてきた。"),
        "ditch": ("The driver swerved to avoid a deep ditch.", "運転手は深い溝を避けるためにハンドルを切った。"),
        "gist": ("I missed some details, but I understood the gist of the lecture.", "細部をいくつか聞き逃したが、講義の大意は理解した。"),
        "omen": ("Many sailors regard a red sky at dawn as an omen of good weather.", "多くの船員は、夜明けの赤い空をよい天気の前兆と考える。"),
        "loot": ("The thieves divided the loot before fleeing the country.", "泥棒たちは国外へ逃げる前に略奪品を分けた。"),
        "sentiment": ("Public sentiment shifted after the report was released.", "その報告書が発表された後、世論が変化した。"),
        "coup": ("Hiring the leading engineer was a major coup for the startup.", "一流の技術者を採用できたことは、その新興企業にとって大きな成功だった。"),
        "dearth": ("A dearth of affordable housing has forced many families to move away.", "手頃な価格の住宅が不足しているため、多くの家族が引っ越しを余儀なくされた。"),
        "ward": ("The nurse checked every patient in the ward.", "看護師は病棟の患者を一人一人確認した。"),
        "entailed": ("The new regulations entailed significant costs for small businesses.", "新しい規制は中小企業に大きな費用を伴った。"),
        "placated": ("The manager placated the customer by replacing the damaged product.", "店長は壊れた商品を交換して客をなだめた。"),
        "mulled": ("She mulled over the proposal before giving her answer.", "彼女は答えを出す前に、その提案を熟考した。"),
        "averted": ("Quick action averted a serious accident.", "素早い行動が重大な事故を回避した。"),
        "alacrity": ("The volunteers accepted the difficult assignment with alacrity.", "ボランティアたちは難しい任務を快活に引き受けた。"),
        "prevarication": ("The witness's prevarication frustrated the investigators.", "証人の言い逃れは捜査官たちをいら立たせた。"),
        "convergence": ("The convergence of several technologies created a new industry.", "いくつもの技術の融合が新しい産業を生み出した。"),
        "nostalgia": ("The old song filled him with nostalgia for his school days.", "その古い歌を聴いて、彼は学生時代への郷愁に包まれた。"),
        "flouted": ("The company flouted the safety regulations for years.", "その会社は何年もの間、安全規則を公然と無視した。"),
        "deified": ("The ancient ruler was deified after his death.", "その古代の支配者は死後に神格化された。"),
        "fermented": ("The fermented vegetables added a sharp flavor to the meal.", "発酵させた野菜が料理に強い風味を加えた。"),
        "coaxed": ("The nurse coaxed the child into taking the medicine.", "看護師は子どもをうまく説得して薬を飲ませた。"),
        "pungent": ("A pungent smell of garlic filled the kitchen.", "強烈なニンニクのにおいが台所に充満した。"),
        "ambivalent": ("She felt ambivalent about moving abroad because she would miss her family.", "家族と離れることになるので、彼女は海外移住に複雑な感情を抱いた。"),
        "lustrous": ("The museum displayed a lustrous silk robe from the eighteenth century.", "その博物館は18世紀の光沢のある絹の衣装を展示した。"),
        "boisterous": ("The boisterous fans celebrated outside the stadium.", "騒々しいファンたちは競技場の外で祝った。"),
        "disheveled": ("He arrived at the interview looking disheveled after a sleepless night.", "彼は一晩眠れず、乱れただらしのない姿で面接に現れた。"),
        "incisive": ("The journalist asked an incisive question about the budget.", "そのジャーナリストは予算について鋭い質問をした。"),
        "suave": ("The suave host made every guest feel comfortable.", "洗練された物腰の柔らかな司会者は、すべての客をくつろがせた。"),
        "perennial": ("Traffic congestion is a perennial problem in the city.", "交通渋滞はその都市の長年の問題だ。"),
        "clemency": ("The prisoner appealed to the governor for clemency.", "囚人は知事に慈悲を求めた。"),
        "solvency": ("The audit confirmed the charity's solvency.", "監査によって、その慈善団体に支払い能力があることが確認された。"),
        "tenure": ("During her tenure as principal, the school improved dramatically.", "彼女が校長を務めていた期間に、学校は大きく改善した。"),
        "censure": ("The committee voted to censure the official for misleading the public.", "委員会は世間を誤解させたとして、その役人を譴責することに投票で決めた。"),
        "unruly": ("The coach struggled to control the unruly crowd.", "コーチは手に負えない観客を抑えるのに苦労した。"),
        "stolid": ("The stolid guard showed no reaction to the loud argument.", "無感動な警備員は、激しい口論にも何の反応も示さなかった。"),
        "lackluster": ("The team delivered a lackluster performance in the final.", "そのチームは決勝で精彩を欠く試合をした。"),
        "nebulous": ("The proposal remained nebulous because its goals were never defined.", "目標が定義されなかったため、その提案は曖昧模糊としたままだった。"),
        "identify with": ("Many young readers identify with the hero's struggle.", "多くの若い読者は主人公の苦闘に共感する。"),
        "reel in": ("The advertisement was designed to reel in new customers.", "その広告は新しい顧客を引き寄せるように作られていた。"),
        "polish off": ("I need to polish off this report before lunch.", "昼食前にこの報告書を仕上げなければならない。"),
        "black out": ("A power failure can black out the entire neighborhood.", "停電によって近所全体が真っ暗になることがある。"),
        "turn up": ("Please turn up the volume so everyone can hear.", "全員に聞こえるように音量を上げてください。"),
        "grow on": ("The song seemed strange at first, but it began to grow on me.", "その歌は最初は変に思えたが、次第に好きになってきた。"),
        "build in": ("The designers decided to build in an emergency backup.", "設計者たちは緊急時の予備機能を組み込むことにした。"),
        "churn out": ("The factory can churn out thousands of bottles each day.", "その工場は毎日何千本ものボトルを大量に作り出せる。"),
        "tamper with": ("Do not tamper with the laboratory equipment.", "実験室の装置をいじくり回さないでください。"),
        "ease off": ("The rain should ease off by evening.", "雨は夕方までには弱まるはずだ。"),
        "trump up": ("They tried to trump up a charge against the journalist.", "彼らはそのジャーナリストに対する罪をでっち上げようとした。"),
        "branch out": ("The family restaurant plans to branch out into catering.", "その家族経営のレストランはケータリング業へ進出する計画だ。"),
        "dole out": ("The charity will dole out blankets to families in need.", "その慈善団体は困っている家族に毛布を少しずつ配る予定だ。"),
        "clam up": ("He tends to clam up whenever the subject of money comes up.", "彼はお金の話題が出るといつも口をつぐみがちだ。"),
        "mete out": ("The judge must mete out punishment fairly.", "裁判官は公正に罰を与えなければならない。"),
        "pluck up": ("She had to pluck up the courage to speak in front of the crowd.", "彼女は群衆の前で話すために勇気を奮い起こさなければならなかった。"),
    },
}


def surface(item: dict) -> str:
    return str(item.get("phrase") if item.get("phrase") else item.get("word", "")).strip()


def write_json(path: Path, data: dict) -> None:
    original = path.read_bytes()
    newline = "\r\n" if b"\r\n" in original else "\n"
    text = json.dumps(data, ensure_ascii=False, indent=2) + "\n"
    if newline == "\r\n":
        text = text.replace("\n", "\r\n")
    path.write_bytes(text.encode("utf-8"))


def main() -> None:
    applied = 0
    for path in sorted(DATA_DIR.glob("vocab_1_*.json")):
        round_id = path.stem.removeprefix("vocab_1_")
        pairs = EXAMPLES.get(round_id)
        if pairs is None:
            raise SystemExit(f"例文データがありません: {round_id}")
        data = json.loads(path.read_text(encoding="utf-8"))
        seen = set()
        for item in [*data.get("words", []), *data.get("idioms", [])]:
            word = surface(item)
            pair = pairs.get(word)
            if pair is None:
                raise SystemExit(f"例文がありません: {path.name} / {word}")
            item["example"], item["exampleTranslation"] = pair
            seen.add(word)
            applied += 1
        extra = set(pairs) - seen
        if extra:
            raise SystemExit(f"データにない例文があります: {path.name} / {sorted(extra)}")
        write_json(path, data)
        print(f"{path.name}: {len(seen)}件")
    print(f"適用した例文: {applied}件")


if __name__ == "__main__":
    main()
